Correctly add authorization header to Subscription.channel.header
inferno-framework/subscriptions-test-kit pull request #14
Opened 2024-12-20 21:34 UTC by karlnaden

# Summary

Previously, when the Subscription Server tests tried to add a Subscription.channel.header value with a bearer token, it did so at the Subscription level instead. Now it does so correctly.

# Testing Guidance

Run the Server tests agains the client tests following the instructions - see suite instructions - but removing the `"header": ["Authorization: Bearer SAMPLE_TOKEN"],` row from the *Workflow Subscription Resource* input on the server tests. Verify that the tests run correctly and that when viewing the client test responsible for verifying the Subscription creation (1.3.01 - Client Subscription Conformance Verification) that the Subscription creation request includes that content under Subscription.channel.

2024-12-23 16:34 UTC, emichaud998 approved these changes
Tested it out and it looks good to me!

2024-12-27 20:32 UTC, tstrass requested changes

2024-12-27 20:32 UTC, tstrass commented on lib/subscriptions_test_kit/common/subscription_conformance_verification.rb
> +        subscription_channel['header'] = [] unless subscription['header'].present?
Seems like you'd need this change as well?

```suggestion
        subscription_channel['header'] = [] unless subscription_channel['header'].present?
```

2024-12-30 17:04 UTC, tstrass approved these changes

2024-12-30 18:10 UTC, merged